---

- name: Initialize all servers
  hosts: all
  roles:
    - initialize

- name: Configure Server
  hosts: server
  roles:
    - server


#- name: Deploy nginx to terminals
#  hosts: attacker:victim
#  roles:
#    - nginx
