---

- name: Install nameserver packages
  apt:
    pkg:
      - bind9
      - bind9utils
      - bind9-doc
  become: yes

- name: Copy over configuration file
  ansible.builtin.copy:
    src: files/named.conf.options
    dest: /etc/bind/named.conf.options
  become: yes

- name: Restart Bind Service
  ansible.builtin.service:
    name: bind9
    state: restarted
  become: yes

- name: Copy over conf.local file
  ansible.builtin.copy:
    src: files/named.conf.options
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: '0755'
  become: yes

- name: Copy over for zone file
  ansible.builtin.copy:
    src: files/for.server.lan
    dest: /etc/bind/for.server.lan
    owner: bind
    group: bind
    mode: '0755'
  become: yes

- name: Copy over rev local file
  ansible.builtin.copy:
    src: files/rev.server.lan
    dest: /etc/bind/rev.server.lan
    owner: bind
    group: bind
    mode: '0755'
  become: yes

- name: Restart Bind Service
  ansible.builtin.service:
    name: bind9
    state: restarted
  become: yes


